version: '3.8'

services:
  user-service:
      build: ./services/user-service
      ports:
        - "5001:5000"
      environment:
        - NODE_ENV=production
        - DATABASE_URL=postgresql://user:password@db:5432/userdb
      depends_on:
        - postgres
      networks:
        - backend

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: travel_app
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672' # Message broker port
      - '15672:15672' # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - '6379:6379'

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
