auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki # ✅ Define path prefix for storage
  replication_factor: 1

schema_config:
  configs:
    - from: 2023-01-01
      store: tsdb # ✅ Use TSDB instead of boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:  # ✅ Correct way to define filesystem storage
  filesystem:
    directory: /loki

limits_config:
  allow_structured_metadata: false # ✅ Disable until schema upgrade is complete

compactor:
  working_directory: /loki/compactor # ✅ Define working directory

# ✅ Disable ring by setting ingester mode to "single binary"
ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory  # ✅ Use in-memory store, not Consul or Memberlist
    final_sleep: 0s