server:
  http_listen_port: 9080

positions:
  filename: /var/log/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push # ✅ Send logs to Loki

scrape_configs:
  - job_name: "docker-logs"
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            time: time
            log: log
    static_configs:
      - targets:
          - localhost
        labels:
          job: "docker-logs"
          host: "localhost"
          __path__: "/var/lib/docker/containers/*/*.log" # ✅ Read Docker container logs
